#!/usr/bin/bash
set -e
echo "Installing Drumee from Debian Packages"
script_dir=$(dirname $(readlink -f $0))
worker=$(basename $0)

env_file=$script_dir/drumee.sh

for arg in "$@"; do
  case $arg in
  --env-file=*)
    env_file="${arg#*=}"
    shift
    ;;
   --env=*)
    env_file="${arg#*=}"
    shift
    ;;
  esac
done

if [ "$worker" = "reinstall" ]; then
  export FORCE_INSTALL=yes
  for p in drumee-ui-pod drumee-server-pod drumee-schemas drumee-infra; do
    apt purge -y $p 
  done
fi

if [ -f $env_file ]; then
  source $env_file
else
  echo Env file $env_file was not found
  exit 1
fi

#
fail() {
  echo $1 was set to invalid value \($2\)
  exit 1
}

use() {
  echo Will use $1=$2v
}

miss() {
  v=$(eval echo '$'$1)
  echo Direcory $v \($1\) was not found. 
  echo Please ensure you have created proper all required directories
  exit 1
}

check() {
  v=$(eval echo '$'$1)
  if [[ "$v" =~ $2 ]]; then
    use $1 $v
  else
    fail $1 $v
  fi
}

check_dir(){
  v=$(eval echo '$'$1)
  if [[ "$v" =~ ^(/+(usr|bin|sys|proc|tmp|etc|lib.*|boot|dev|sbin|opt|media|mnt|vmlinuz.*|lost.+|snap|root|run|initrd.*)/)|/+$ ]]; then
    echo It is not safe to install $1 under directory $v
    exit 1
  fi
  is_path="^(/.+)(/.+)*$"
  if [ -d "$v" ]; then
    check $1 $is_path
  else
    miss $1
  fi
}

is_email="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$"
check PUBLIC_IP4 "^([0-9]{1,3})(\.[0-9]{1,3}){3}$"
if [ "$PUBLIC_IP6" = "" ]; then
  echo No IP, skipped.
else
  check PUBLIC_IP6 "^([[:xdigit:]]{1,4})(:[[:xdigit:]]{0,4})*$"
fi 
check DRUMEE_DOMAIN_NAME "^([a-zA-Z0-9_\-]+)(\.[a-zA-Z0-9_\-]+){1,}$"
check ADMIN_EMAIL $is_email

if [ "$ACME_EMAIL_ACCOUNT" = "" ]; then
  export ACME_EMAIL_ACCOUNT=$ADMIN_EMAIL
else 
  check ACME_EMAIL_ACCOUNT $is_email
fi

if [ "$DRUMEE_DB_DIR" = "" ]; then
  export DRUMEE_DB_DIR=/srv/db
  mkdir -p $DRUMEE_DB_DIR
fi

if [ "$DRUMEE_DATA_DIR" = "" ]; then
  export DRUMEE_DATA_DIR=/data
  mkdir -p $DRUMEE_DATA_DIR
fi

check_dir DRUMEE_DB_DIR
check_dir DRUMEE_DATA_DIR

if [ "$STORAGE_BACKUP" != "" ]; then
  check_dir STORAGE_BACKUP
else
  echo ************************ WARNING *****************************
  echo * You didn\'t specify a backup storage locatiion             *
  echo * in case of failure, you may lost partly or all of you data *
  echo **************************************************************
fi

export INFRA_COMPONENTS=all
if [ "$DRUMEE_REPO" = "" ]; then
  export DRUMEE_REPO=app.drumee.com
fi

$script_dir/bin/install-packages 

echo Dependencies installed
echo Starting Drumee installation
sleep 2
if [ -x /usr/bin/nsupdate ]; then
  $script_dir/bin/install-drumee
else
  echo DNS utils nsupdate is missing. Abborted
fi
